services:
  db:
    container_name: pg_primdev_container
    image: postgres:12.9-alpine
    restart: always
    environment:
      POSTGRES_USER: primdev
      POSTGRES_PASSWORD: primdevjaya
      POSTGRES_DB: primdevDB
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer_primdev_container
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080"
